import {
  addDoc,
  collection,
  CollectionReference,
  doc,
  DocumentReference,
  Firestore,
  setDoc,
} from "firebase/firestore";
import { stringify } from "querystring";

const states = [
  {
    abbrev: "AL",

    name: "Alabama",
    capital: "Montgomery",
  },
  { abbrev: "AZ", name: "Arizona", capital: "Phoenix" },
  { abbrev: "CA", name: "California", capital: "Sacramento" },
];

function addSingleDoc(db: Firestore) {
  // Use filesystem syntax for document path
  const il_doc: DocumentReference = doc(db, "states/IL");
  // Add a new document with our own id (IL)
  setDoc(il_doc, {
    name: "Illinois",
    capital: "Springfield",
  }).then(() => {
    console.log(`New document with ID ${il_doc.id} inserted`);
  });

  // Use arguments syntax for document path
  const mi_doc: DocumentReference = doc(db, "states", "MI");
  // Add a new document with our own id (MI)
  setDoc(mi_doc, {
    name: "Michigan",
    capital: "Lansing",
  }).then(() => {
    console.log("MI added");
  });

  const coll: CollectionReference = collection(db, "states");
  // Add a new document with autogenerated id
  addDoc(coll, { name: "Ohio", capital: "Columbus" }).then(
    (newDoc: DocumentReference) => {
      console.log(`New document with ID ${newDoc.id} inserted`);
    }
  );
}

function addMultipleDocsWithPromise(db: Firestore) {
  // Option #1: Use Promise.all
  const proms = states.map(
    (z: { abbrev: string; name: string; capital: string }) => {
      const d = doc(db, "states", z.abbrev);
      return setDoc(d, { name: z.name, capital: z.capital });
    }
  );
  Promise.all(proms).then(() => {
    console.log(`Done inserting ${states.length} docs to Firestore`);
  });
}

function addMultipleDocsWithAwait(db: Firestore) {
  states.forEach(
    async (z: { abbrev: string; name: string; capital: string }) => {
      const d = doc(db, "states", z.abbrev);
      await setDoc(d, { name: z.name, capital: z.capital });
    }
  );
}
function addDocInSubCollection(db: Firestore) {
  const michCities = collection(db, "states", "MI", "cities");
  addDoc(michCities, {
    name: "Grand Rapids",
    lat: 42.963795,
    lon: -85.670006,
  });
  addDoc(michCities, {
    name: "Lansing",
    lat: 42.732536,
    lon: -84.555534,
  });
  addDoc(michCities, {
    name: "Detroit",
    lat: 42.331429,
    lon: -83.045753,
  });
  const GR = doc(db, "states", "MI", "cities", "GRR");
  setDoc(GR, { name: "Grand Rapids", lon: -85.670006, lat: 42.963795 });
}

export function run(db: Firestore) {
  addSingleDoc(db);
  // addMultipleDocsWithPromise(db);
  addDocInSubCollection(db);
  addMultipleDocsWithAwait(db);
}
